DROP TABLE IF EXISTS wcf1_shoutbox_entry;
CREATE TABLE wcf1_shoutbox_entry (
	entryID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID INT(10) NOT NULL DEFAULT 0,
	username VARCHAR(255) NOT NULL DEFAULT '',
	time INT(20) NOT NULL DEFAULT 0,
	message MEDIUMTEXT,
	ipAddress VARCHAR(15) NOT NULL DEFAULT '',
	KEY (time)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;